{
  "formatVersion": "1.1",
  "component": {
    "group": "ASMPlugin",
    "module": "asmPlugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3lxw4tbz6nf73d66ma2yxdg77y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "asmPlugin-unspecified.jar",
          "url": "asmPlugin-unspecified.jar",
          "size": 16677,
          "sha512": "d38b5345d00dea1c8ec8dca0864b2d5af8f7867d509df6cc61881e9b37f19f26d20d5104118d60222d670ee844120b631462753e1bbde0fd1b0d5af758a16e45",
          "sha256": "e86e2828feb77aa3da191cef3184e9441573b4da1693e04249246f24bb2d2361",
          "sha1": "25dcbfaf00232873884c59b30ec3aec5b83509ae",
          "md5": "e9393428f69bfa9aec8b48f7bec2653d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "asmPlugin-unspecified.jar",
          "url": "asmPlugin-unspecified.jar",
          "size": 16677,
          "sha512": "d38b5345d00dea1c8ec8dca0864b2d5af8f7867d509df6cc61881e9b37f19f26d20d5104118d60222d670ee844120b631462753e1bbde0fd1b0d5af758a16e45",
          "sha256": "e86e2828feb77aa3da191cef3184e9441573b4da1693e04249246f24bb2d2361",
          "sha1": "25dcbfaf00232873884c59b30ec3aec5b83509ae",
          "md5": "e9393428f69bfa9aec8b48f7bec2653d"
        }
      ]
    }
  ]
}
